[package]
name = "httpserver"
version = "1.0.5"
edition = "2021"
authors = ["kiven <kivensoft@gmail.com>"]
description = "A simple, asynchronous log library"

[features]
english = []

[dependencies]
tokio = { version = "1.36", features = ["rt", "rt-multi-thread", "net", "parking_lot"] }
hyper = { version = "1.1", features = [ "http1", "server" ] }
hyper-util = { version = "0.1", features = [ "server", "http1", "tokio" ] }
http-body-util = "0.1"
form_urlencoded = "1.2"
urlencoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
compact_str = { version = "0.7", features = ["serde", "bytes"] }
fnv = "1.0"
anyhow = "1.0"
log = "0.4"
async-trait = "0.1"
itoa = "1.0"
